### ISSUE TITLE
求助啊！关于CSS布局的问题

### ISSUE THREAD

**Issue by TakWolf** [TakWolf/takwolf.github.io#2]
![38a6c106-12ff-11e6-8906-3cc0261bea31](https://cloud.githubusercontent.com/assets/6064962/15249142/ae9816ba-1950-11e6-979a-b2a17a4eb820.png)

我现在就想要实现上面这个布局，怎么实现左中右布局？
左侧头像是44px，右侧心是 42px（24px图案+8内边距留白），所有空白边距都为16px
怎么搞都不对，左浮动之后，右侧内容总是跑到下面一行

研究了一下CNode的，还发现了posotion:relative，没搞懂啊？

@alsotang @liygheart

**Comment by TakWolf** [comment]
@XGHeaven 

本来用flex实现了一下，成功了，然后运行发现这个不兼容旧手机，悲了个剧。

![screenshot_2016-05-13-21-29-20](https://cloud.githubusercontent.com/assets/6064962/15249401/ec4850dc-1951-11e6-9e0a-9dcdb9bb1ed6.png)

因为还有这样的布局，右侧有两个图标，右侧还需要拆分

这样布局大概的思路是什么？

**Comment by liygheart** [comment]
bootstrap里有一个media样式，有.media-left .media-body .media-right
http://v3.bootcss.com/components/#media

**Comment by liygheart** [comment]
flex布局的语法
http://www.ruanyifeng.com/blog/2015/07/flex-grammar.html

**Comment by alsotang** [comment]
我css从来都是乱来的。。。如果你 flex 搞对了的话，就放弃旧手机吧。。

2016-05-13 23:18 GMT+08:00 朋也 <notifications@github.com>:

**Comment by TakWolf** [comment]
研究了一下v2ex的样式，最后用表格实现了。。。

**Comment by liygheart** [comment]
我也推荐使用flex实现

TakWolf <notifications@github.com>于2016年5月14日周六 05:22写道：

**Comment by TakWolf** [comment]
@liygheart   
我希望最低能够兼容到Android 4.0（API 14），实际测试了一下，flex只能兼容到Android 4.4（API 19），这个兼容度太低了，至少希望兼容到14

**Comment by alsotang** [comment]
用table实现布局已经是十年前的事情了，早就不被推荐了，下次有机会还是用 float 来调吧。

2016-05-14 9:02 GMT+08:00 TakWolf <notifications@github.com>:

**Comment by TakWolf** [comment]
@alsotang 好的，发现知识欠缺严重。本来还以为没啥呢，实际写起来才发现连基本布局都搞不定。。

**Comment by alsotang** [comment]
我从来都搞不定，js 的问题我还行，css 感觉反人类

2016-05-14 18:10 GMT+08:00 TakWolf <notifications@github.com>:
